# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectTitle', models.CharField(max_length=100)),
                ('CommitAmount', models.FloatField(default=0.0)),
                ('ExpectedReturn', models.FloatField(default=0.0)),
                ('CommitDuration', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('SymbolChoice', models.CharField(max_length=200)),
                ('Comments', models.TextField()),
                ('IsUndertaken', models.BooleanField(default=False)),
            ],
        ),
    ]
