# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('perc_change', models.FloatField(default=0.0)),
                ('fundsent', models.CharField(max_length=10)),
            ],
        ),
    ]
